WEBSOCKET_HOST = "0.0.0.0"
WEBSOCKET_PORT = 8765
OPERATION_TIMEOUT_SECONDS = 0.15

PWM_RANGE = 255
PWM_MIN = -PWM_RANGE
PWM_MAX = PWM_RANGE
PWM_FREQUENCY = 1000

LEFT_PWM_PIN = 24
LEFT_DIR_PIN = 25
LEFT_REVERSE = False

RIGHT_PWM_PIN = 18
RIGHT_DIR_PIN = 23
RIGHT_REVERSE = False
