WEBSOCKET_HOST = "0.0.0.0"
WEBSOCKET_PORT = 8765
# The browser sends operation messages every 50ms. Stop within three send
# intervals if operation updates cease.
OPERATION_TIMEOUT_SECONDS = 0.15

DISTANCE_TRIG_PIN = 22
DISTANCE_ECHO_PIN = 27
DISTANCE_TIMEOUT_SECONDS = 0.03
DISTANCE_MEASUREMENT_INTERVAL_SECONDS = 0.06
DISTANCE_MIN_CM = 2.0
DISTANCE_MAX_CM = 400.0
OBSTACLE_DISTANCE_CM = 20.0

BUZZER_PIN = 17
BUZZER_FREQUENCY = 2000
BUZZER_DUTY_CYCLE = 128

PWM_RANGE = 255
PWM_MIN = -PWM_RANGE
PWM_MAX = PWM_RANGE
PWM_FREQUENCY = 1000

LEFT_PWM_PIN = 24
LEFT_DIR_PIN = 25
LEFT_REVERSE = False

RIGHT_PWM_PIN = 18
RIGHT_DIR_PIN = 23
RIGHT_REVERSE = False
