WEBSOCKET_HOST = "0.0.0.0"
WEBSOCKET_PORT = 8765
# The browser sends operation messages every 50ms. Stop within three send
# intervals if operation updates cease.
OPERATION_TIMEOUT_SECONDS = 0.15

LEFT_DISTANCE_TRIG_PIN = 12
LEFT_DISTANCE_ECHO_PIN = 16
RIGHT_DISTANCE_TRIG_PIN = 20
RIGHT_DISTANCE_ECHO_PIN = 21
DISTANCE_SENSOR_PINS = (
    ("left", LEFT_DISTANCE_TRIG_PIN, LEFT_DISTANCE_ECHO_PIN),
    ("right", RIGHT_DISTANCE_TRIG_PIN, RIGHT_DISTANCE_ECHO_PIN),
)
DISTANCE_SENSOR_IDS = tuple(sensor_id for sensor_id, _, _ in DISTANCE_SENSOR_PINS)
DISTANCE_TIMEOUT_SECONDS = 0.03
# Keep triggers from the two front sensors far enough apart to avoid acoustic
# cross-talk. Each individual sensor is therefore sampled about every 120 ms.
DISTANCE_MEASUREMENT_INTERVAL_SECONDS = 0.06
DISTANCE_MIN_CM = 2.0
DISTANCE_MAX_CM = 400.0
OBSTACLE_DISTANCE_CM = 20.0
OBSTACLE_CLEAR_DISTANCE_CM = 25.0
DISTANCE_INVALID_LIMIT = 3

BUZZER_PIN = 17
BUZZER_FREQUENCY = 2000
BUZZER_DUTY_CYCLE = 128

PWM_RANGE = 255
PWM_MIN = -PWM_RANGE
PWM_MAX = PWM_RANGE
PWM_FREQUENCY = 1000

LEFT_PWM_PIN = 25
LEFT_DIR_PIN = 24
LEFT_REVERSE = False

RIGHT_PWM_PIN = 23
RIGHT_DIR_PIN = 18
RIGHT_REVERSE = False
